### ISSUE TITLE
win10下初始化问题

### ISSUE THREAD

**Issue by benemorphy** [GAMEOMETRICS/VisualGraph-python#1]
win10下，命令行启动界面时，只出现右侧边菜单，其他菜单项都没有了
![image](https://user-images.githubusercontent.com/12068967/217818553-4701f29e-46ea-4e76-8c4a-cec462645958.png)
由于命令行缺乏提示信息，也不清楚是什么模块的问题。
![image](https://user-images.githubusercontent.com/12068967/217818817-0c146387-0311-4bd6-ac74-d37a0d401180.png)

**Comment by GAMEOMETRICS** [comment]
你这个问题确实很奇怪，我今天又试了一遍，没出现类似的问题，你直接clone之后运行就这个样子吗？

**Comment by benemorphy** [comment]
也许是python环境问题，请问你的python是哪个版本？



在 2023-02-10 08:18:32，"GAMEOMETRICS" ***@***.***> 写道：

你这个问题确实很奇怪，我今天又试了一遍，没出现类似的问题，你直接clone之后运行就这个样子吗？

**Comment by GAMEOMETRICS** [comment]
> 也许是python环境问题，请问你的python是哪个版本？ 在 2023-02-10 08:18:32，"GAMEOMETRICS" ***@***.***> 写道： 你这个问题确实很奇怪，我今天又试了一遍，没出现类似的问题，你直接clone之后运行就这个样子吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我python直接用的anacoda3自带的那个3.9.13 然后PySide6是6.4.2

**Comment by benemorphy** [comment]
是初始窗口位置的问题。
运行程序后用win+右箭头最大化，就好了

















在 2023-02-12 09:56:24，"GAMEOMETRICS" ***@***.***> 写道：

也许是python环境问题，请问你的python是哪个版本？ 在 2023-02-10 08:18:32，"GAMEOMETRICS" @.> 写道： 你这个问题确实很奇怪，我今天又试了一遍，没出现类似的问题，你直接clone之后运行就这个样子吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

我python直接用的anacoda3自带的那个3.9.13 然后PySide6是6.4.2
